// js/data.js
// Mock clinic dataset around Los Angeles.
// 你以后可以把这里替换为真实数据（比如从 CSV 转成 JS）

export const CLINICS = [
  {
    name: "UCLA Counseling Center",
    lat: 34.0689,
    lon: -118.4452,
    type: "outpatient",
    address: "221 Westwood Plaza, Los Angeles, CA",
    email: "counseling@ucla.edu",
    phone: "(310) 825-0768",
    hours: "Mon–Fri 8:00–17:00",
    appointment: "Online booking; same-week intake slots",
    focus: ["anxiety", "depression", "cbt"],
    online: true,
    acceptsUndiagnosed: true,
    multilingual: true,
    noGuardianRequired: true,
    costModel: "sliding",
    waitTimeDays: 7
  },
  {
    name: "LA Community Mental Health Center",
    lat: 34.0407,
    lon: -118.2468,
    type: "hospital",
    address: "100 Main St, Los Angeles, CA",
    email: "info@lacommunitymh.org",
    phone: "(213) 555-1234",
    hours: "24/7 emergency & inpatient",
    appointment: "Walk-in for urgent care; referral for ongoing care",
    focus: ["anxiety", "depression", "trauma", "medication"],
    online: false,
    acceptsUndiagnosed: true,
    multilingual: true,
    noGuardianRequired: false,
    costModel: "insurance",
    waitTimeDays: 3
  },
  {
    name: "Westside CBT & Anxiety Clinic",
    lat: 34.0522,
    lon: -118.35,
    type: "specialized",
    address: "500 Olympic Blvd, Los Angeles, CA",
    email: "frontdesk@westsidecbt.com",
    phone: "(310) 555-7777",
    hours: "Mon–Sat 9:00–19:00",
    appointment: "Phone screening then scheduled CBT sessions",
    focus: ["anxiety", "cbt", "trauma"],
    online: true,
    acceptsUndiagnosed: true,
    multilingual: false,
    noGuardianRequired: true,
    costModel: "private",
    waitTimeDays: 14
  },
  {
    name: "Downtown Urgent Care for Mental Health",
    lat: 34.0489,
    lon: -118.2578,
    type: "urgent_care",
    address: "220 S Hope St, Los Angeles, CA",
    email: "urgent@dtmhcare.org",
    phone: "(213) 555-9090",
    hours: "Mon–Sun 10:00–22:00",
    appointment: "Walk-in only; short crisis stabilization",
    focus: ["crisis", "trauma"],
    online: false,
    acceptsUndiagnosed: true,
    multilingual: true,
    noGuardianRequired: false,
    costModel: "sliding",
    waitTimeDays: 1
  },
  {
    name: "South LA Family Therapy Center",
    lat: 33.98,
    lon: -118.28,
    type: "outpatient",
    address: "1200 S Vermont Ave, Los Angeles, CA",
    email: "hello@southlafamily.org",
    phone: "(323) 555-6060",
    hours: "Tue–Sat 9:00–18:00",
    appointment: "Phone intake; priority for youth & families",
    focus: ["family", "depression", "anxiety"],
    online: true,
    acceptsUndiagnosed: true,
    multilingual: true,
    noGuardianRequired: false,
    costModel: "sliding",
    waitTimeDays: 10
  },
  {
    name: "Eastside Psychiatry & Medication Clinic",
    lat: 34.05,
    lon: -118.2,
    type: "specialized",
    address: "1500 Cesar Chavez Ave, Los Angeles, CA",
    email: "psychiatry@eastsideclinic.com",
    phone: "(323) 555-8888",
    hours: "Mon–Fri 9:00–17:30",
    appointment: "Referral or PCP recommendation preferred",
    focus: ["medication", "depression", "anxiety"],
    online: false,
    acceptsUndiagnosed: false,
    multilingual: false,
    noGuardianRequired: true,
    costModel: "insurance",
    waitTimeDays: 21
  },
  {
    name: "Student Wellness & Safe Space Center",
    lat: 34.0224,
    lon: -118.2851,
    type: "outpatient",
    address: "Campus Center, University District",
    email: "wellness@campuscenter.edu",
    phone: "(213) 555-2222",
    hours: "Mon–Fri 9:00–20:00",
    appointment: "Drop-in peer support + short-term counseling",
    focus: ["anxiety", "depression", "family"],
    online: true,
    acceptsUndiagnosed: true,
    multilingual: true,
    noGuardianRequired: true,
    costModel: "free",
    waitTimeDays: 2
  },
  {
    name: "Neighborhood Trauma Recovery Program",
    lat: 34.08,
    lon: -118.3,
    type: "specialized",
    address: "600 Trauma Way, Los Angeles, CA",
    email: "recovery@traumaprogram.org",
    phone: "(213) 555-3333",
    hours: "Mon–Thu 10:00–18:00",
    appointment: "Referral from ER / shelter / community orgs",
    focus: ["trauma", "family"],
    online: false,
    acceptsUndiagnosed: true,
    multilingual: false,
    noGuardianRequired: false,
    costModel: "insurance",
    waitTimeDays: 28
  },
  {
    name: "West LA Mindful Psychiatry & Therapy",
    lat: 34.05,
    lon: -118.45,
    type: "specialized",
    address: "2200 Bundy Dr, Los Angeles, CA",
    email: "info@mindfulwestla.com",
    phone: "(310) 555-4444",
    hours: "Mon–Sat 9:00–19:00",
    appointment: "Online form; telehealth available",
    focus: ["medication", "cbt", "anxiety"],
    online: true,
    acceptsUndiagnosed: true,
    multilingual: false,
    noGuardianRequired: true,
    costModel: "private",
    waitTimeDays: 5
  },
  {
    name: "Central Youth & Teen Mental Health Hub",
    lat: 34.045,
    lon: -118.27,
    type: "outpatient",
    address: "300 Youth Ave, Los Angeles, CA",
    email: "teencare@centralsupport.org",
    phone: "(213) 555-1212",
    hours: "Mon–Sat 11:00–20:00",
    appointment: "Parent or self-referral; walk-in triage",
    focus: ["anxiety", "depression", "family"],
    online: true,
    acceptsUndiagnosed: true,
    multilingual: true,
    noGuardianRequired: false,
    costModel: "sliding",
    waitTimeDays: 4
  }
];

